site_name: "Web3j Corda"
site_description: "Documentation portal for the web3j Corda Blockchain Library"
site_author: "Web3 Labs"
site_url: "https://corda.web3j.io/"

repo_name: "web3j/corda"
repo_url: "https://github.com/web3j/corda"

copyright: "Copyright &copy; 2017-2019 Web3 Labs Ltd"

nav:
  - Quickstart : quickstart.md
  - Getting Started : dependencies.md
  - Connect to Corda Node : connecting_to_node.md
  - Generating Client Wrappers : generating.md
  - Client Wrappers : client.md
  - Working with Client Wrappers : usage.md
  - Network Queries : network.md
  - Command Line Tools: command_line_tools.md
  - Writing tests: tests.md
  - Examples: examples.md
  - Support: support.md

# Configuration
theme:
  name: "material"
  logo: "images/web3j-corda-logo.png"
  language: "en"
  feature:
    tabs: true
  palette:
    primary: "white"
    accent: "deep-orange"

markdown_extensions:
  - pymdownx.tasklist

extra_css:
  - "stylesheets/extra.css"
  - "stylesheets/github.css"

extra_javascript:
  - 'javascripts/highlight.pack.js'
  - 'javascripts/index.js'
